#!/bin/sh

######################
# ## Just computer   #
######################

if [ "$1" = "off" ]
then
    xrandr --output DP5 --off &&\
    xrandr --output DP3 --off &&\
    xrandr --output DP4 --off &&\
    xrandr --output eDP1 --auto
fi

###################################################
# ## In a presentation to connecto to a Projector #
###################################################

if [ "$1" = "vga" ]
then
    xrandr --output VGA1 --auto --left-of LVDS1
fi

##########################################################
# ## In the office with 3 screens and laptop screen off. #
##########################################################

if [ "$1" = "office" ]
then
    xrandr --output eDP1 --off &&\
    xrandr --output DP5 --off &&\
    xrandr --output DP4 --off &&\
    xrandr --addmode DP4 1920x1080 &&\
    xrandr --addmode DP5 1920x1080 &&\
    xrandr --addmode DP3 1920x1080 &&\
    xrandr --output DP3 --mode 1920x1080 &&\
    xrandr --output DP4 --mode 1920x1080 --left-of DP3 &&\
    xrandr --output DP5 --mode 1920x1080 --right-of DP3
fi

###################
# ## Home Monitor #
###################

if [ "$1" = "home" ]
then
    xrandr --output LVDS1 --auto --pos 0x1000 --output VGA1 --auto --pos 1366x0
fi
